### ISSUE TITLE
【交互优化】图片只有一张的时候，感觉隐藏调切换的功能比较好

### ISSUE THREAD

**Issue by OwnGhy** [zWingz/react-image#2]
### 问题
一张图片的时候，有切换的按钮给用户一种可以切换蒙层下方资源的错觉，造成误解；并且只有一张图片的时候图片资源又重新reload了一次，稍显多余。

### 解决办法
1. 只有一张图片的时候直接隐藏切换的icon并禁止切换
2. 或者，提供一个禁用切换图片的api

**Comment by OwnGhy** [comment]
因为现在的项目开发比较着急使用，如果您没有时间的话，我可以自己修改了提 PR 吗？😳

**Comment by zWingz** [comment]
@OwnGhy 你可以提, 测试没问题我就merge

**Comment by OwnGhy** [comment]
好的 感谢，我先试试

**Comment by OwnGhy** [comment]
您好，我本地想使用npm link测试，然后npm run build 的时候说循环引用了，请问您有遇到这个问题吗

**Comment by OwnGhy** [comment]
```
Circular dependency: src/lib/Image/index.tsx -> src/lib/ImgPreview/index.ts -> src/lib/ImgPreview/ImgPreview.tsx -> src/lib/Image/index.tsx
```

报错是这样的

**Comment by zWingz** [comment]
@OwnGhy 已发新版本

**Comment by OwnGhy** [comment]
您好，我又试了一下，这边有个需求就是视频和图片同时预览，然后可以互相切换，请问可以加上这个功能吗？

不知道符不符合你写这个插件的初衷～

**Comment by OwnGhy** [comment]
暂时不用了，感觉也不是特别符合这个组件的初衷，感谢感谢
